### ISSUE TITLE
Issues with the yml

### ISSUE THREAD

**Issue by Kernelalive** [astrid-project/astrid-framework#2]
Hello,
for java v11 the default certs causing a problem with ssl. Demote Java to v8.

**Comment by Kernelalive** [comment]
:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of [ \\t\\r\\n], \"#\", \"input\", \"filter\", \"output\" at line 1, column 1 (byte 1)", :backtrace=>["/home/ubuntu/logstash/logstash-7.5.0/logstash-core/lib/logstash/compiler.rb:41:in `compile_imperative'", "/home/ubuntu/logstash/logstash-7.5.0/logstash-core/lib/logstash/compiler.rb:49:in `compile_graph'", "/home/ubuntu/logstash/logstash-7.5.0/logstash-core/lib/logstash/compiler.rb:11:in `block in compile_sources'", "org/jruby/RubyArray.java:2584:in `map'", "/home/ubuntu/logstash/logstash-7.5.0/logstash-core/lib/logstash/compiler.rb:10:in `compile_sources'", "org/logstash/execution/AbstractPipelineExt.java:156:in `initialize'", "org/logstash/execution/JavaBasePipelineExt.java:47:in `initialize'", "/home/ubuntu/logstash/logstash-7.5.0/logstash-core/lib/logstash/java_pipeline.rb:26:in `initialize'", "/home/ubuntu/logstash/logstash-7.5.0/logstash-core/lib/logstash/pipeline_action/create.rb:36:in `execute'", "/home/ubuntu/logstash/logstash-7.5.0/logstash-core/lib/logstash/agent.rb:326:in `block in converge_state'"]}


i have the issue above. I think it is caused from a wrong yml file.

**Comment by alexcarrega** [comment]
Updated the code. Now the yml file is ok.
